<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>ajoutcommande</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="ajoutcommande" />
<meta name="description" content="ajoutcommande" />
<meta name="generator" content="Dolibarr 19.0.2 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="72" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="d738813f" async src="/javascript.js.php?website=<?php echo $websitekey; ?>"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-ajoutcommande">
<?php
// Résoudre le chemin absolu vers main.inc.php
$main_inc_path = $_SERVER['DOCUMENT_ROOT'] . '/main.inc.php';

// Inclure le fichier de Dolibarr
require_once $main_inc_path;
session_start();

// Vérifier si l'utilisateur est connecté
if (!isset($_SESSION['valid'])) {
    header("Location: Login.php");
    exit;
}

// Récupérer l'ID de l'utilisateur connecté et l'ID de la société
$user_id = (int)$_SESSION['id']; // Assurez-vous que l'ID de l'utilisateur est entier

// Afficher l'ID de la société
echo "<p>ID de la société : $user_id</p>";

// Récupérer product_id depuis l'URL
$product_id = isset($_GET['product_id']) ? (int)$_GET['product_id'] : 0;

// Vérifier si product_id est valide (à adapter selon vos besoins)
if ($product_id <= 0) {
    die("Erreur : ID de produit non spécifié ou invalide.");
}

// Connexion à la base de données Dolibarr
global $db;

// Vérifier la connexion à la base de données
if (!$db) {
    echo "Erreur de connexion à la base de données";
    exit;
}

// Fonction pour générer un ref unique
function generateUniqueRef($db) {
    $base_ref = 'prov';
    $new_ref = '';
    $tries = 0;

    do {
        // Générer une nouvelle référence
        $new_ref = $base_ref . uniqid();
        
        // Vérifier si la référence existe déjà
        $query_check_ref = "SELECT COUNT(*) as count FROM " . MAIN_DB_PREFIX . "commande WHERE ref = '$new_ref'";
        $result_check_ref = $db->query($query_check_ref);
        $count = $db->fetch_object($result_check_ref)->count;
        
        // Limiter le nombre d'essais pour éviter une boucle infinie
        $tries++;
        if ($tries > 10) {
            // En cas d'échec après 10 tentatives, générer une référence aléatoire unique
            $new_ref = $base_ref . uniqid();
            break;
        }
    } while ($count > 0);

    return $new_ref;
}

// Vérifier si le formulaire a été soumis
if (isset($_POST['submit'])) {
    // Échapper la date du champ de formulaire de manière sécurisée
    $date = $db->escape($_POST['date']);

    // Vérifier si la société existe dans la base de données
    $query_check_soc = "SELECT rowid FROM " . MAIN_DB_PREFIX . "societe WHERE rowid = $user_id";
    $result_check_soc = $db->query($query_check_soc);
    $num_rows = $db->num_rows($result_check_soc);

    if ($num_rows > 0) {
        // Générer un ref unique
        $ref = generateUniqueRef($db);

        // Calculer le total TTC de la commande
        $total_ttc = 0;
        if (isset($_SESSION['panier'][$user_id]) && count($_SESSION['panier'][$user_id]) > 0) {
            foreach ($_SESSION['panier'][$user_id] as $item) {
                $total_ttc += $item['prix'] * $item['quantite'];
            }
        }

        // Préparation de la requête SQL pour l'insertion de commande
        $query_insert_commande = "INSERT INTO " . MAIN_DB_PREFIX . "commande (ref, date_commande, fk_soc, fk_statut, total_ht) 
                                  VALUES ('$ref', '$date', $user_id, 1, $total_ttc)";
        $result_insert = $db->query($query_insert_commande);

        // Vérification si la requête a réussi
        if ($result_insert) {
            // Récupérer l'ID de la commande insérée
            $commande_id = $db->last_insert_id(MAIN_DB_PREFIX . 'commande');

            // Insertion des lignes de commande
            if (isset($_SESSION['panier'][$user_id]) && count($_SESSION['panier'][$user_id]) > 0) {
                foreach ($_SESSION['panier'][$user_id] as $item) {
                    // Échapper les valeurs pour éviter les injections SQL
                    $fk_product = (int)$item['id'];
                    $qty = (int)$item['quantite'];
                    $prix_unitaire = (float)$item['prix'];
                    
                    $query_insert_commande_line = "INSERT INTO " . MAIN_DB_PREFIX . "commandedet (fk_commande, fk_product, qty, subprice) 
                                                   VALUES ($commande_id, $fk_product, $qty, $prix_unitaire)";
                    $result_insert_line = $db->query($query_insert_commande_line);
                    if (!$result_insert_line) {
                        echo "<p>Erreur lors de l'ajout de la ligne de commande : " . $db->lasterror() . "</p>";
                    }
                }
                // Redirection vers la page commandes.php après l'ajout de la commande
                header("Location: Commandes.php");
                exit;
            } else {
                echo "<p>Aucun produit trouvé dans le panier pour l'utilisateur.</p>";
            }
        } else {
            echo "<p>Erreur lors de l'ajout de la commande : " . $db->lasterror() . "</p>";
        }
    } else {
        echo "<p>Erreur : La société avec l'ID $user_id n'existe pas.</p>";
    }
}
?>

<!DOCTYPE html>
<html lang="fr">
<body>
    <div class="zai-container">
        <?php include('header.php'); ?>
        <main class="zai-main">
            <h1>Ajouter Commande</h1>
            <!-- Affichage de l'ID du produit -->
            <p>ID du produit sélectionné : <?php echo $product_id; ?></p>
            
            <form action="" method="post">
                <div class="form-group">
                    <label for="date">Date</label>
                    <input type="date" name="date" id="date" autocomplete="off" value="<?php echo date('Y-m-d'); ?>" readonly>
                </div>

                <!-- Affichage du produit sélectionné -->
                <?php 
                // Vérifier si le produit spécifié est présent dans le panier
                $found = false;
                if (isset($_SESSION['panier'][$user_id]) && count($_SESSION['panier'][$user_id]) > 0) {
                    foreach ($_SESSION['panier'][$user_id] as $item) {
                        if ($item['id'] == $product_id) {
                            $found = true;
                            ?>
                            <div class="form-group">
                                <label>Référence: <?php echo $item['ref']; ?></label>
                            </div>
                            <div class="form-group">
                                <label>Label: <?php echo $item['label']; ?></label>
                            </div>
                            <div class="form-group">
                                <label>Prix: <?php echo $item['prix']; ?> TND</label>
                            </div>
                            <div class="form-group">
                                <label>Quantité: <?php echo $item['quantite']; ?></label>
                            </div>
                            <?php
                            break; // Sortir de la boucle une fois trouvé
                        }
                    }
                }
                if (!$found) {
                    echo "<p>Le produit spécifié n'est pas dans le panier.</p>";
                }
                ?>

                <div class="login-btn">
                    <input type="submit" name="submit" value="Ajouter Commande">
                </div>
            </form>
        </main>
    </div>
</body>
</html>
</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 72); dolWebsiteIncrementCounter(9, "page", 72);
// END PHP ?>
