<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>commandes</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="commandes" />
<meta name="description" content="commandes" />
<meta name="generator" content="Dolibarr 19.0.2 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="75" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="5dae120f" async src="/javascript.js.php?website=<?php echo $websitekey; ?>"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-commandes">
<?php
// Résoudre le chemin absolu vers main.inc.php
$main_inc_path = $_SERVER['DOCUMENT_ROOT'] . '/main.inc.php';
// Inclure le fichier de Dolibarr
require_once $main_inc_path;

session_start();
if (!isset($_SESSION['valid'])) {
    include 'login.php';
    exit;
}

// Connexion à la base de données Dolibarr
global $db;

if ($db) {
    // Récupérer l'ID de la société connectée
    $societe_id = $_SESSION['id'];

    // Initialisation des variables de recherche
    $ref = isset($_GET['ref']) ? $_GET['ref'] : '';
    $filter_statut = isset($_GET['filter-statut']) ? $_GET['filter-statut'] : ''; // Filtre statut

    $sql = "SELECT rowid AS commande_id, ref, date_commande, total_ht, total_ttc, total_tva, date_cloture, fk_statut, facture
            FROM " . MAIN_DB_PREFIX . "commande 
            WHERE fk_soc = " . intval($societe_id) . " AND fk_statut != 0";

    // Ajout de la condition de recherche par référence si elle est définie
    if (!empty($ref)) {
        $sql .= " AND ref LIKE '%" . $db->escape($ref) . "%'";
    }

    // Ajout des conditions de filtre de statut
    if (!empty($filter_statut)) {
        if ($filter_statut == '1') {
            $sql .= " AND fk_statut = 1";
        } elseif ($filter_statut == '2') {
            $sql .= " AND fk_statut = 2";
        } elseif ($filter_statut == '3') {
            $sql .= " AND fk_statut = 3 AND facture = 0";
        } elseif ($filter_statut == '4') {
            $sql .= " AND fk_statut = 3 AND facture = 1";
        }
    }

    // Exécuter la requête SQL
    $result = $db->query($sql);
} else {
    echo "Erreur de connexion à la base de données";
    exit;
}
$link_to_page_imp = dol_buildpath('detailscommande.php', 1);
$link_to_page = dol_buildpath('commandes.php', 1);
?>

<?php includeContainer('header'); ?>
<?php includeContainer('aside_bar'); ?>

<section id="mysection1" contenteditable="true">
    <main>
        <div class="ccontainer">
            <div class="table-container">
                <table class="oorder-table">
                    <thead>
                        <tr>
                            <th>N° DE COMMANDE</th>
                            <th>DATE</th>
                            <th>MONTANT HT</th>
                            <th>MONTANT TVA</th>
                            <th>MONTANT TTC</th>
                            <th>DATE DE LIVRAISON</th>
                            
                            <style>
                                .filter-statut {
                                    position: absolute;
                                    top: 0;
                                    width: 100%;
                                    height: 80%;
                                    left: 10px;
                                    font-size: 14px;
                                }
                                
                                #filter-statut {
                                    opacity: 0;
                                    height: 100%;
                                    width: 100%;
                                    padding: 10px;
                                    cursor: pointer;
                                }
                                
                                .box-filter {
                                    display: flex;
                                    justify-content: center;
                                    align-items: center;
                                }
                                
                            </style>
                            
                            <th style="position: relative;">
                                <div class="filter-statut">
                                    <form action="<?php echo htmlspecialchars($link_to_page); ?>" method="get">
                                        <input type="hidden" name="website" value="ebusinessTester1">
                                        <input type="hidden" name="pageref" value="commandes">
                                        <label></label>
                                        <select name="filter-statut" id="filter-statut" onchange="this.form.submit()">
                                            <option value="" <?php if ($filter_statut == '') echo 'selected'; ?>>Tout</option>
                                            <option value="1" <?php if ($filter_statut == '1') echo 'selected'; ?>>Validée</option>
                                            <option value="2" <?php if ($filter_statut == '2') echo 'selected'; ?>>Envoi en cours</option>
                                            <option value="3" <?php if ($filter_statut == '3') echo 'selected'; ?>>Livrée</option>
                                            <option value="4" <?php if ($filter_statut == '4') echo 'selected'; ?>>Livrée-Facturé</option>
                                        </select>
                                    </form>
                                </div>
                                <span class="box-filter">
                                    STATUT<i class='bx bx-filter' style="margin-left: 4px;"></i>
                                </span>
                            </th>
                            
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $total_ht_sum = 0;
                        $total_tva_sum = 0;
                        $total_ttc_sum = 0;

                        if ($result) {
                            while ($row = $db->fetch_object($result)) {
                                echo "<tr>";
                                echo "<td>{$row->ref}</td>";
                                echo "<td>" . date("d/m/Y", strtotime($row->date_commande)) . "</td>";
                                echo "<td>" . number_format($row->total_ht, 3, ',', ' ') . " TND</td>";
                                echo "<td>" . number_format($row->total_tva, 3, ',', ' ') . "</td>";
                                echo "<td>" . number_format($row->total_ttc, 3, ',', ' ') . " TND</td>";

                                // Ajouter les valeurs aux totaux
                                $total_ht_sum += $row->total_ht;
                                $total_tva_sum += $row->total_tva;
                                $total_ttc_sum += $row->total_ttc;

                                // Afficher la date de clôture seulement si elle n'est pas NULL
                                echo "<td>" . ($row->date_cloture ? date("d/m/Y", strtotime($row->date_cloture)) : '') . "</td>";

                                // Statut
                                if ($row->fk_statut == 1) {
                                    echo "<td>Validée</td>";
                                } elseif ($row->fk_statut == 2) {
                                    echo "<td>Envoi en cours</td>";
                                } elseif ($row->fk_statut == 3 && $row->facture == 0) {
                                    echo "<td>Livrée</td>";
                                } elseif ($row->fk_statut == 3 && $row->facture == 1) {
                                    echo "<td>Livrée-Facturé</td>"; 
                                } else {
                                    echo "<td>Autre</td>";
                                }

                                echo "<td><a href=\"" . htmlspecialchars($link_to_page_imp . '?commande_id=' . $row->commande_id) . "\" class=\"aaction-btn\">Imprimer</a></td>";
                                echo "</tr>";
                            }
                            $db->free($result);
                        } else {
                            echo "<tr><td colspan='8'>Aucune commande trouvée</td></tr>";
                        }
                        ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2"><strong>Total</strong></td>
                            <td><strong><?php echo number_format($total_ht_sum, 3, ',', ' ') . " TND"; ?></strong></td>
                            <td><strong><?php echo number_format($total_tva_sum, 3, ',', ' '); ?></strong></td>
                            <td><strong><?php echo number_format($total_ttc_sum, 3, ',', ' ') . " TND"; ?></strong></td>
                            <td colspan="4"></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </main>
</section>

</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 75); dolWebsiteIncrementCounter(9, "page", 75);
// END PHP ?>
