<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>aside_bar</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="aside_bar" />
<meta name="description" content="" />
<meta name="generator" content="Dolibarr 19.0.2 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="73" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="23e7e3a7" async src="/javascript.js.php?website=<?php echo $websitekey; ?>"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-aside_bar">
<!-- Enter here your HTML content. Add a section with an id tag and tag contenteditable="true" if you want to use the inline editor for the content  -->
<?php 
// Résoudre le chemin absolu vers main.inc.php
$main_inc_path = $_SERVER['DOCUMENT_ROOT'] . '/main.inc.php';

// Inclure le fichier de Dolibarr
require_once $main_inc_path;

// Démarrer la session
session_start();
if (!isset($_SESSION['valid'])) {
    include 'login.php';
    exit;
}

// Connexion à la base de données Dolibarr
global $db;

/**
 * Récupère le nombre total de tickets pour une société donnée.
 *
 * @param object $db L'objet de connexion à la base de données.
 * @param int $societe_id L'ID de la société.
 * @return int Le nombre total de tickets.
 */
function getTotalTickets($db, $societe_id) {
    $total_count_ticket = 0;

    $query_total_tickets = "SELECT COUNT(*) AS total_count_ticket FROM " . MAIN_DB_PREFIX . "ticket WHERE fk_soc = " . intval($societe_id);
    $result_total_tickets = $db->query($query_total_tickets);

    if ($result_total_tickets && $db->num_rows($result_total_tickets) > 0) {
        $row_total_tickets = $db->fetch_object($result_total_tickets);
        $total_count_ticket = $row_total_tickets->total_count_ticket;
    }

    return $total_count_ticket;
}

// Vérifier la connexion à la base de données
if ($db) {
    // Récupérer l'ID de la société connectée
    $societe_id = $_SESSION['id'];

    // Utiliser la fonction pour récupérer le nombre total de tickets
    $total_count_ticket = getTotalTickets($db, $societe_id);
}

?>


<div class="container-profil-grid">

<aside contenteditable="true">
    
    <div class="aside-cate-container">
        
        <a class="aside-cate<?php echo ($websitepage->ref == 'profil' ? ' active-link' : ''); ?>" href="profil.php"><i class='bx bxs-user'></i><p class="cate-link">Mon profil</p></a>
        <a class="aside-cate<?php echo ($websitepage->ref == 'proposition_commerciale' ? ' active-link' : ''); ?>" href="proposition_commerciale.php"><i class='bx bx-money-withdraw'></i><p class="cate-link">Devis</p></a>
        <a class="aside-cate<?php echo ($websitepage->ref == 'commandes' ? ' active-link' : ''); ?>" href="commandes.php"><i class='bx bx-cart-alt' ></i><p class="cate-link">Commandes</p></a>
        <a class="aside-cate<?php echo ($websitepage->ref == 'facture' ? ' active-link' : ''); ?>" href="facture.php"><i class='bx bx-receipt' ></i><p class="cate-link">Factures</p></a>
        <a class="aside-cate<?php echo ($websitepage->ref == 'ticket' ? ' active-link' : ''); ?>" href="ticket.php"><i class='bx bx-support'></i><p class="cate-link">Tickets <span class="nbr-tickets"><?php echo number_format($total_count_ticket); ?></span></p></a>
        <!--<a class="aside-cate<?php echo ($websitepage->ref == 'ticket' ? ' active-link' : ''); ?>" href="ticket.php"><i class='bx bx-archive-in' ></i><p class="cate-link">Tickets</p></a>-->
    </div>
</aside>

<?php if($total_count_ticket < 10) : ?>
    <style>
        .nbr-tickets {
            color: var(--color-first);
            padding: 1px 8px;
            margin-left: 4px;
            border-radius: 50%;
            position: relative;
            top: 1px;
            background: var(--color-second);
        }
        .active-link .nbr-tickets {
            color: var(--color-third);
            padding: 1px 8px;
            margin-left: 0px;
            border-radius: 50%;
            position: relative;
            top: 0px;
            background: transparent;
        }
    </style>
<?php elseif($total_count_ticket < 100) : ?>
    <style>
        .nbr-tickets {
            color: var(--color-first);
            padding: 4px 4px;
            margin-left: 4px;
            border-radius: 50%;
            position: relative;
            top: 1px;
            background: var(--color-second);
        }
        .active-link .nbr-tickets {
            color: var(--color-third);
            padding: 5px 5px;
            margin-left: 0px;
            border-radius: 50%;
            position: relative;
            top: 0px;
            background: transparent;
        }
    </style>
<?php elseif($total_count_ticket > 99) : ?>
    <style>
        .nbr-tickets {
            color: var(--color-first);
            padding: 8px 3px;
            margin-left: 4px;
            font-size: 19px;
            border-radius: 50%;
            position: relative;
            top: 1px;
            background: var(--color-second);
        }
        .active-link .nbr-tickets {
            color: var(--color-third);
            padding: 8px 3px;
            margin-left: 0px;
            font-size: 19px;
            border-radius: 50%;
            position: relative;
            top: 0px;
            background: transparent;
        }
    </style>
<?php endif; ?>






<style>
    aside {
        position: relative;
        background: var(--color-first);
        width: 14vw;
        height: 100%;
        padding: 34px 10px 34px 22px;
    }
    
    .aside-cate-container {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        gap: 38px;
        width: 100%;
    }

    .aside-cate {
        position: relative;
        width: 100%;
        display: flex;
        align-items: center;
        gap: 10px;
    }
    
    .aside-cate i {
        color: var(--color-second);
        font-size:  28px;
    }
    
    .aside-cate.active-link i {
        color: var(--color-third);
    }
    
    .cate-link {
        position: relative;
        width: 100%;
        text-align: left;
        font-family: "Roboto", sans-serif !important;
        font-size: 22px !important;
        color: var(--color-second) !important;
        letter-spacing: 1px;
        font-weight: 500 !important;
        margin: 0 !important;
    }
    
    .active-link {
        background: var(--color-second);
        padding: 10px 16px 10px 20px;
        border-radius: 14px 0 0 14px;
        width: 108%;
    }
    .active-link .cate-link {
        color: var(--color-third) !important;
    }
    
    
    
</style>

</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 73); dolWebsiteIncrementCounter(9, "page", 73);
// END PHP ?>
