<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>detailscommande</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="detailscommande" />
<meta name="description" content="" />
<meta name="generator" content="Dolibarr 19.0.2 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="77" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="d738813f" async src="/javascript.js.php?website=<?php echo $websitekey; ?>"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-detailscommande">
<?php
// Inclure les fichiers nécessaires et démarrer la session
$main_inc_path = $_SERVER['DOCUMENT_ROOT'] . '/main.inc.php';
require_once $main_inc_path;

session_start();

// Vérifier la connexion de l'utilisateur
if (!isset($_SESSION['valid'])) {
    include 'login.php';
    exit;
}

// Connexion à la base de données Dolibarr
global $db;

if (!$db) {
    echo "Erreur de connexion à la base de données";
    exit;
}

// Récupérer et nettoyer l'ID de commande à partir de l'URL
$commande_id = intval($_GET['commande_id']);

// Récupérer les informations de la commande depuis la base de données
$sql_check_commande = "SELECT rowid, ref FROM " . MAIN_DB_PREFIX . "commande WHERE rowid = $commande_id";
$result_check_commande = $db->query($sql_check_commande);

if ($db->num_rows($result_check_commande) == 0) {
    echo "Commande avec l'ID $commande_id introuvable";
    exit;
}

// Récupérer la référence de la commande
$commande = $db->fetch_object($result_check_commande);
$commande_ref = $commande->ref;

// Construire le chemin du fichier PDF
$pdf_path = $_SERVER['DOCUMENT_ROOT'] . '/documents/commande/' . $commande_ref . '/' . $commande_ref . '.pdf';

// Vérifier si le fichier PDF existe
if (file_exists($pdf_path)) {
    // Envoyer les en-têtes HTTP pour forcer le téléchargement
    header('Content-Disposition: attachment; filename="' . basename($pdf_path) . '"');
    header('Content-Length: ' . filesize($pdf_path));
    header('Pragma: public');
    header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    header('Expires: 0');

    // Désactiver la mise en mémoire tampon de sortie
    if (ob_get_level()) {
        ob_end_clean();
    }

    // Lire et envoyer le fichier PDF au navigateur
    readfile($pdf_path);
    exit;
} else {
    // Si le fichier n'existe pas, afficher un message d'erreur
    echo "Le fichier PDF pour la commande $commande_ref n'existe pas.";
    exit;
}
?>

</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 77); dolWebsiteIncrementCounter(9, "page", 77);
// END PHP ?>
