<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>profil</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="profil" />
<meta name="description" content="profil" />
<meta name="generator" content="Dolibarr 19.0.2 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="90" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="a1a8de54" async src="/javascript.js.php?website=<?php echo $websitekey; ?>"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-profil">
<?php
// Résoudre le chemin absolu vers main.inc.php
$main_inc_path = $_SERVER['DOCUMENT_ROOT'] . '/main.inc.php';

// Inclure le fichier de Dolibarr
require_once $main_inc_path;

// Démarrer la session
session_start();
if (!isset($_SESSION['valid'])) {
    include 'login.php';
    exit;
}

// Connexion à la base de données Dolibarr
global $db;

// Vérifier la connexion à la base de données
if ($db) {
    // Récupérer l'ID de la société connectée
    $societe_id = $_SESSION['id'];

    // Récupérer les détails de la société
    $query_societe = "SELECT nom, email, phone, address, zip, town, logo FROM " . MAIN_DB_PREFIX . "societe WHERE rowid = " . intval($societe_id);
    $result_societe = $db->query($query_societe);

    if ($result_societe && $db->num_rows($result_societe) > 0) {
        $row_societe = $db->fetch_object($result_societe);
        $societe_nom = $row_societe->nom;
        $societe_email = $row_societe->email;
        $societe_phone = $row_societe->phone;
        $societe_address = $row_societe->address;
        $societe_zip = $row_societe->zip;
        $societe_town = $row_societe->town;
        $societe_logo = $row_societe->logo;

        $logo_path = '/viewimage.php?modulepart=societe&file=' . $societe_id . '/' . $societe_logo;

    } else {
        echo "Société non trouvée.";
        exit;
    }

    // Calculer la somme totale des propositions commerciales
    $query_total_ttc_propal = "SELECT SUM(total_ttc) AS total_ttc_sum_propal, SUM(total_ht) AS total_ht_sum_propal FROM " . MAIN_DB_PREFIX . "propal WHERE fk_soc = " . intval($societe_id);
    $result_total_ttc_propal = $db->query($query_total_ttc_propal);
    $total_ttc_sum_propal = 0;
    $total_ht_sum_propal = 0;

    if ($result_total_ttc_propal && $db->num_rows($result_total_ttc_propal) > 0) {
        $row_total_ttc_propal = $db->fetch_object($result_total_ttc_propal);
        $total_ttc_sum_propal = $row_total_ttc_propal->total_ttc_sum_propal;
        $total_ht_sum_propal = $row_total_ttc_propal->total_ht_sum_propal;
    }

    // Calculer la somme totale des factures clients sauf celles avec fk_statut = 0
   /* $query_total_factures = "SELECT SUM(total_ttc) AS total_ttc_sum_factures, SUM(total_ht) AS total_ht_sum_factures FROM " . MAIN_DB_PREFIX . "facture WHERE fk_soc = " . intval($societe_id) . " AND fk_statut != 0";
    $result_total_factures = $db->query($query_total_factures);
    $total_ttc_sum_factures = 0;
    $total_ht_sum_factures = 0;

    if ($result_total_factures && $db->num_rows($result_total_factures) > 0) {
        $row_total_factures = $db->fetch_object($result_total_factures);
        $total_ttc_sum_factures = $row_total_factures->total_ttc_sum_factures;
        $total_ht_sum_factures = $row_total_factures->total_ht_sum_factures;
    }
    */
    $query_total_factures = "SELECT 
                            SUM(total_ttc) AS total_ttc_sum_factures, 
                            SUM(total_ht) AS total_ht_sum_factures 
                         FROM " . MAIN_DB_PREFIX . "facture 
                         WHERE fk_soc = " . intval($societe_id) . " 
                           AND fk_statut != 0
                           AND type != 3";
$result_total_factures = $db->query($query_total_factures);

$total_ttc_sum_factures = 0;
$total_ht_sum_factures = 0;

if ($result_total_factures) {
    $data = $result_total_factures->fetch_assoc();
    $total_ttc_sum_factures = $data['total_ttc_sum_factures'] ? $data['total_ttc_sum_factures'] : 0;
    $total_ht_sum_factures = $data['total_ht_sum_factures'] ? $data['total_ht_sum_factures'] : 0;
}


    // Calculer la somme totale des commandes
    $query_total_commandes = "SELECT SUM(total_ttc) AS total_ttc_sum_commandes, SUM(total_ht) AS total_ht_sum_commandes FROM " . MAIN_DB_PREFIX . "commande WHERE fk_soc = " . intval($societe_id);
    $result_total_commandes = $db->query($query_total_commandes);
    $total_ttc_sum_commandes = 0;
    $total_ht_sum_commandes = 0;

    if ($result_total_commandes && $db->num_rows($result_total_commandes) > 0) {
        $row_total_commandes = $db->fetch_object($result_total_commandes);
        $total_ttc_sum_commandes = $row_total_commandes->total_ttc_sum_commandes;
        $total_ht_sum_commandes = $row_total_commandes->total_ht_sum_commandes;
    }

    // Calculer le total des tickets
    $query_total_tickets = "SELECT COUNT(*) AS total_count_ticket FROM " . MAIN_DB_PREFIX . "ticket WHERE fk_soc = " . intval($societe_id);
    $result_total_tickets = $db->query($query_total_tickets);
    $total_count_ticket = 0;

    if ($result_total_tickets && $db->num_rows($result_total_tickets) > 0) {
        $row_total_tickets = $db->fetch_object($result_total_tickets);
        $total_count_ticket = $row_total_tickets->total_count_ticket;
    }

    // Calculer les créances
    $sql = "SELECT f.rowid AS facture_id, f.ref, f.datec, f.date_lim_reglement, f.total_ht, f.total_tva, f.total_ttc, f.multicurrency_total_ttc, f.fk_statut, f.type, f.paye,
                   (SELECT SUM(pf.amount) FROM " . MAIN_DB_PREFIX . "paiement_facture pf WHERE pf.fk_facture = f.rowid) AS total_amount_recu
            FROM " . MAIN_DB_PREFIX . "facture f
            WHERE f.fk_soc = " . intval($societe_id);
    $total_ht_sum = 0;
    $total_tva_sum = 0;
    $total_ttc_sum = 0;
    $total_recu_sum = 0;
    $total_creance_sum = 0;

    // Exécuter la requête pour calculer les créances
    $result = $db->query($sql);
    if ($result) {
        while ($row = $db->fetch_object($result)) {
            $total_ht_sum += $row->total_ht;
            $total_tva_sum += $row->total_tva;
            $total_ttc_sum += $row->total_ttc;
            $total_recu_sum += $row->total_amount_recu;
        }
        $total_creance_sum = $total_ttc_sum - $total_recu_sum;
    }

    // Calculer les acomptes restants
    $query_acomptes = "SELECT SUM(amount_ttc) AS total_acomptes
                       FROM " . MAIN_DB_PREFIX . "societe_remise_except
                       WHERE fk_facture IS NULL AND fk_facture_source IN (
                           SELECT rowid FROM " . MAIN_DB_PREFIX . "facture
                           WHERE fk_soc = " . intval($societe_id) . " AND type = 3
                       )";
    $result_acomptes = $db->query($query_acomptes);
    $total_acomptes = 0;

    if ($result_acomptes && $db->num_rows($result_acomptes) > 0) {
        $row_acomptes = $db->fetch_object($result_acomptes);
        $total_acomptes = $row_acomptes->total_acomptes;
    }

    // Calculer les avoirs restants
    $query_avoirs = "SELECT SUM(amount_ttc) AS total_avoirs
                     FROM " . MAIN_DB_PREFIX . "societe_remise_except
                       WHERE fk_facture IS NULL AND fk_facture_source IN (
                         SELECT rowid FROM " . MAIN_DB_PREFIX . "facture
                         WHERE fk_soc = " . intval($societe_id) . " AND type = 2
                     )";
    $result_avoirs = $db->query($query_avoirs);
    $total_avoirs = 0;

    if ($result_avoirs && $db->num_rows($result_avoirs) > 0) {
        $row_avoirs = $db->fetch_object($result_avoirs);
        $total_avoirs = $row_avoirs->total_avoirs;
    }

    // Calculer les acomptes utilisés
    $query_acomptes_utilises = "SELECT SUM(amount_ttc) AS total_acomptes_utilises
                                FROM " . MAIN_DB_PREFIX . "societe_remise_except
                       WHERE fk_facture IS NOT NULL AND fk_facture_source IN (
                         SELECT rowid FROM " . MAIN_DB_PREFIX . "facture
                         WHERE fk_soc = " . intval($societe_id) . " AND type = 3
                     )";
    $result_acomptes_utilises = $db->query($query_acomptes_utilises);
    $total_acomptes_utilises = 0;

    if ($result_acomptes_utilises && $db->num_rows($result_acomptes_utilises) > 0) {
        $row_acomptes_utilises = $db->fetch_object($result_acomptes_utilises);
        $total_acomptes_utilises = $row_acomptes_utilises->total_acomptes_utilises;
    }

    // Calculer les avoirs utilisés
    $query_avoirs_utilises = "SELECT SUM(amount_ttc) AS total_avoirs_utilises
                              FROM " . MAIN_DB_PREFIX . "societe_remise_except
                       WHERE fk_facture IS NOT NULL AND fk_facture_source IN (
                         SELECT rowid FROM " . MAIN_DB_PREFIX . "facture
                         WHERE fk_soc = " . intval($societe_id) . " AND type = 2
                     )";
    $result_avoirs_utilises = $db->query($query_avoirs_utilises);
    $total_avoirs_utilises = 0;

    if ($result_avoirs_utilises && $db->num_rows($result_avoirs_utilises) > 0) {
        $row_avoirs_utilises = $db->fetch_object($result_avoirs_utilises);
        $total_avoirs_utilises = $row_avoirs_utilises->total_avoirs_utilises;
    }
}
?>




<?php includeContainer('header'); ?>

<?php includeContainer('aside_bar'); ?>

<div class="grid-right-side">
    
    <div class="profil-conteneur">
        <div class="left-side-profil">
                                  
            <img src="<?php echo $logo_path; ?>" alt="Photo de Profil" class="profil-photo">

            <h1 class="profile-name"><?php echo htmlspecialchars($societe_nom); ?>!</h1>
            <div class="line"></div>
            <p><b>Email</b><?php echo htmlspecialchars($societe_email); ?></p>
            <p><b>Phone</b><?php echo htmlspecialchars($societe_phone); ?></p>
    
            <p><b>Adresse </b><?php echo htmlspecialchars($societe_address) . ' , ' . htmlspecialchars($societe_zip) . ' - Tunisie - ' .  htmlspecialchars($societe_town); ?></p>

        </div>
        
        <div class="right-side-profil">
          
            <div class="total-card">
                <div class="total-card-title">
                    <h5>Mes devis</h3>
                </div>
                <div class="total-card-price">
                    <p><b>Total TTC</b><?php echo number_format($total_ttc_sum_propal, 3, ',', ' '); ?> TND</p>
                    <p class="light-ht"><b>Total HT</b><?php echo number_format($total_ht_sum_propal, 3, ',', ' '); ?> TND</p>

                    <div class="detail-container">
                        <div class="line"></div>
                        <a href="proposition_Commerciale.php" class="more-details">Plus de détails</a>
                    </div>
                </div>
            </div>
            
            <div class="total-card">
                <div class="total-card-title">
                    <h5>Mes commandes</h3>
                </div>
                <div class="total-card-price">
                <p><b>Total TTC</b><?php echo number_format($total_ttc_sum_commandes, 3, ',', ' '); ?> TND</p>
                    <p class="light-ht"><b>Total HT</b><?php echo number_format($total_ht_sum_commandes, 3, ',', ' '); ?> TND</p>
                    <div class="detail-container">
                        <div class="line"></div>
                        <a href="commandes.php" class="more-details">Plus de détails</a>
                    </div>
                </div>
            </div>
            
            <!--<div style="width: 100%;display: flex; justify-content: center;">-->
                
            <div class="total-card">
                <div class="total-card-title">
                    <h5>Mes factures</h3>
                </div>
                <div class="total-card-price">
                    <p><b>Total TTC</b><?php echo number_format($total_ttc_sum_factures, 3, ',', ' '); ?> TND</p>
                    <p class="light-ht"><b>Total HT</b><?php echo number_format($total_ht_sum_factures, 3, ',', ' '); ?> TND</p>

                    <div class="detail-container">
                        <div class="line"></div>
                        <a href="facture.php" class="more-details">Plus de détails</a>
                    </div>
                </div>
            </div>
            
            <!--</div>-->
            
            
            
            
             <div class="total-card">
                <div class="total-card-title">
                    <h5>Mes avoirs</h3>
                </div>
                <div class="total-card-price">
                       <p><b>Total TTC</b><?php echo number_format($total_avoirs, 3, ',', ' '); ?> TND</p>

                    <div class="detail-container">
                        <div class="line"></div>
                        <a href="avoir.php" class="more-details">Plus de détails</a>
                    </div>
                </div>
            </div>
            
             
            
            <div class="total-card">
                <div class="total-card-title">
                    <h5>Mes acomptes</h3>
                </div>
                <div class="total-card-price">
                     <p><b>Total TTC</b><?php echo number_format($total_acomptes, 3, ',', ' '); ?> TND</p>

                    <div class="detail-container">
                        <div class="line"></div>
                        <a href="acompte.php" class="more-details">Plus de détails</a>
                    </div>
                </div>
            </div>
            
            
            <!--<div class="total-card">-->
            <!--    <div class="total-card-title">-->
            <!--        <h5>Mes tickets</h3>-->
            <!--    </div>-->
            <!--    <div class="total-card-price">-->
            <!--        <p><b>Total  </b><?php echo number_format($total_count_ticket); ?></p>-->
            <!--        <div class="detail-container">-->
            <!--            <div class="line"></div>-->
            <!--            <a href="ticket.php" class="more-details">Plus de détails</a>-->
            <!--        </div>-->
            <!--    </div>-->
            <!--</div>-->
            
            
        
            
            
          
        </div>
    </div>
    
    
<!--    <div class="profile-container">-->
<!--        <div class="profile-left">-->
<!--            <img src="image/Zai.tn/header/mahmoud.jpeg" alt="Photo de Profil" class="profile-photo">-->
                            
<!--            <h1 class="profile-name"><?php echo htmlspecialchars($societe_nom); ?>!</h1>-->
<!--            <p class="profile-info">Email : utilisateur@example.com</p>-->
<!--            <p class="profile-info">Téléphone : +33 1 23 45 67 89</p>-->
<!--            <p class="profile-info">Adresse : 123 Rue Exemple, Paris, France</p>-->
<!--            <p class="profile-info">Fonction : Profession</p>-->
<!--        </div>-->
<!--        <div class="profile-right">-->
<!--            <div class="card">-->
<!--                <h2>Total des Commandes</h2>-->
<!--<p>Total HT: <?php echo number_format($total_ht_sum_commandes, 2, ',', ' '); ?> TND</p>-->
<!--                        <li><a href="Commandes.php"><button class="btn">Plus</button></a></li>            </div>-->
<!--            <div class="card">-->
<!--                <h2>Total des Factures</h2>-->
<!--<p>Total HT: <?php echo number_format($total_ht_sum_factures, 2, ',', ' '); ?> TND</p>-->
<!--                        <li><a href="Facture.php"><button class="btn">Plus</button></a></li>            </div>-->
<!--            <div class="card">-->
<!--                <h2>Total des Propositions</h2>-->
<!--<p>Total HT: <?php echo number_format($total_ht_sum_propal, 2, ',', ' '); ?> TND</p>-->
<!--                        <li><a href="Proposition_Commerciale.php"><button class="btn">Plus</button></a></li>            </div>-->
<!--             <div class="card">-->
<!--                <h2>Total des tickets</h2>-->
<!--<p>Total des tickets est :  </p>-->
<!--                        <li><a href="Ticket.php"><button class="btn">Plus</button></a></li>            </div>-->
<!--        </div>-->
<!--    </div>-->
</div>


</div>


<style>
    .container-profil-grid {
        position: relative;
        display: grid;
        grid-template-columns: 14vw 86vw;
        min-height: 92vh;
    }
    
    .grid-right-side {
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        width:100%;
        height: 100%;
        background: var(--color-second);
        padding: 7vh 0;
    }
    
    .profil-conteneur {
        position: relative;
        width: 85%;
        display: flex;
        height: auto;
        background: #ffffff;
        border-radius: 32px;
        box-shadow: 0 4px 6px rgb(0 0 0 / 20%);
        border: solid 2px var(--color-first);
        overflow: hidden;
    }
    
    .left-side-profil {
        position: relative;
        /*width: 50%;*/
        background: var(--color-first);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 4px;
        padding: 50px;
    }
    
    .right-side-profil {
        position: relative;
        /*width: 60%;*/
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-wrap: wrap;
        gap: 30px;
        padding: 45px 20px;
    }
    
    .left-side-profil .profil-photo {
        width: 240px;
        height: 240px;
        border-radius: 50%;
        border: solid 3px #ffffff;
    }
    
    .left-side-profil h1{
        font-family: "JetBrains Mono", monospace;
        font-size: 58px;
        color: var(--color-second);
        text-transform: capitalize;
        letter-spacing:2px;
        text-align: center;
    }
    
    
    .left-side-profil .line {
        width: 35%;
        height: 1px;
        margin: 0 0 30px 0;
        background: white;
    }
    
    .left-side-profil b {
        color: var(--color-second);
        margin-right: 5px;
    }
    
    .left-side-profil p {
        color: #9f9f9f;
        font-family: "Roboto", sans-serif;
        letter-spacing: 1px;
        font-size: 22px;
        text-align: center;
    }
    
    
    
    
    
    
    .total-card {
        position: relative;
        width: 360px;
        display: flex;
        flex-direction: column;
        border: solid 2px var(--color-first);
        border-radius: 24px;
        box-shadow: 0 4px 6px rgb(0 0 0 / 16%);
        overflow:hidden;
        display: flex;
        flex-direction: column;
        transition: .3s;
        will-change: transform;
    }
    
    .total-card:hover {
           transform: scale(102%);
    }
    .total-card:hover .total-card-title {
        background: #4e82cf;
    }
    
    
    
    .total-card-title {
        position: relative;
        background: var(--color-first);
        padding: 8px 16px;
        transition: .3s;
    }
    
    .total-card h5 {
        text-align: center;
        color : #ddeaff;
    }
    
    .total-card-price {
        position: relative;
        width: 100%;
        height: 100%;
        padding: 18px;
    }
    
    .total-card-price p {
        font-family: "Roboto", sans-serif;
        font-size: 26px;
        color: var(--color-third);
        font-weight: 500;
        margin-bottom: 1.1vh;
    }
    
    .total-card-price b {
        margin-right: 14px;
        font-weight: 500;
        color: var(--color-first);
    }
    
    .total-card-price .line {
        position: relative;
        height: 1px;
        width: 35%;
        background: var(--color-first);
        right: -18px;
    }
    
    .detail-container {
        display: flex;
        flex-direction: column;
        align-items: flex-end;
        gap: 10px;
    }
    
    .more-details {
        font-size: 20px !important;
        color: var(--color-first) !important;
        transition: .3s;
    }
    
    .more-details:hover {
        color: black;
        letter-spacing: 1px;
    }
    
    .light-ht {
        font-weight: 300 !important;
        font-size: 22px !important;
        margin-bottom: 1.4vh !important;
    }
    .light-ht b{
        font-weight: 400 !important;
    }
    

</style>
</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 90); dolWebsiteIncrementCounter(9, "page", 90);
// END PHP ?>
