<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>ticket</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="ticket" />
<meta name="description" content="" />
<meta name="generator" content="Dolibarr 19.0.2 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="92" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="542bfc01" async src="/javascript.js.php?website=<?php echo $websitekey; ?>"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-ticket">
<?php
// Résoudre le chemin absolu vers main.inc.php
$main_inc_path = $_SERVER['DOCUMENT_ROOT'] . '/main.inc.php';

// Inclure le fichier de Dolibarr
require_once $main_inc_path;

session_start();
if (!isset($_SESSION['valid'])) {
    include 'login.php';
    exit;
}

// Connexion à la base de données Dolibarr
global $db;

if ($db) {
    // Récupérer l'ID de la société connectée
    $societe_id = $_SESSION['id'];

    // Construction de la requête SQL pour les tickets de la société
    $sql = "SELECT ref, subject, message, datec FROM " . MAIN_DB_PREFIX . "ticket
            WHERE fk_soc = " . intval($societe_id);

    // Exécuter la requête SQL
    $result = $db->query($sql);
} else {
    echo "Erreur de connexion à la base de données";
    exit;
}
?>
<?php includeContainer('header'); ?>
<?php includeContainer('aside_bar'); ?>

<section id="mysection1" contenteditable="true">
    <main>
        <div class="ccontainer">
          <div class="table-container">
            <table class="oorder-table">
                <thead>
                    <tr>
                        <th>N° DE Ticket</th>
                        <th>Subject</th>
                        <th>Date de création</th>
                        <th>Message</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if ($result) {
                        while ($row = $db->fetch_object($result)) {
                            echo "<tr>";
                            echo "<td>{$row->ref}</td>";
                            echo "<td>{$row->subject}</td>";
                            echo "<td>" . date("d/m/Y", strtotime($row->datec)) . "</td>";
                            echo "<td>{$row->message}</td>";
                            echo "</tr>";
                        }
                        $db->free($result);
                    } else {
                        echo "<tr><td colspan='4'>Aucun ticket trouvé</td></tr>";
                    }
                    ?>
                </tbody>
            </table>
        </div>    
        
        
        <div class="ticket-blank">
            
            <a href="https://demo.cieloo.io/custom/ticketplus/index.php?v=tickets" target="blank"><b>Accédez au Centre de Support </b></a>
            <a href=""><p>Ouvrez un Ticket pour une Prise en Charge Rapide par Nos Équipes</p></a>
            
        </div>
        
        
        </div>
    </main>
</section>

        <style>
        
            .ticket-blank {
                display: flex;
                margin: 6vh 0;
                width: 100%;
                justify-content: center;
                align-items: center;
                flex-direction: column;
            }
            
            .ticket-blank a {
                font-size: 22px !important;
                color: var(--color-first);
            }
            
            .ticket-blank a:hover {
                color: #2668c7 !important;
            }
            
            .ticket-blank a b {
                transition: .2s;
            }
            
            .ticket-blank a:hover b {
                color: #4a75b3 !important;
            }
            
            
            
        </style>

</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 92); dolWebsiteIncrementCounter(9, "page", 92);
// END PHP ?>
