<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>Header</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="Header" />
<meta name="description" content="Header" />
<meta name="generator" content="Dolibarr 19.0.2 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="82" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="3088aadb" async src="/javascript.js.php?website=<?php echo $websitekey; ?>"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-header">
<?php 
session_start();

?>

<section id="header" contenteditable="true">
    
    <nav class="newNavbar<?php echo ($websitepage->ref == 'catalogue' || $websitepage->ref == 'index' ? ' transparent' : ''); ?>">
            
            <a class="navbar-brand" href="index.php">
                <img src="image/ebusinessTester1/header/logo_zai_b 1.png" alt="Logo" style="max-height: 150px; width: 150px;">
            </a>

            

            <div class="container-link" id="navbarNav">
                
                <a class="nav-link<?php echo ($websitepage->ref == 'index' ? ' active' : ''); ?>" href="index.php"><?php echo $weblangs->trans("Home"); ?></a>
                 
                <!--<a class="nav-link<?php echo ($websitepage->ref == 'profil' ? ' active' : ''); ?>" href="profil.php"><?php echo $weblangs->trans("Profil"); ?></a>-->
                 
                <a class="nav-link<?php echo ($websitepage->ref == 'produit' ? ' active' : ''); ?>" href="catalogue.php"><?php echo $weblangs->trans("Catalogue"); ?></a>
           
                <a class="nav-link<?php echo ($websitepage->ref == 'panier' ? ' active' : ''); ?>" href="panier.php"><?php echo $weblangs->trans("Panier"); ?></a>
              
            </div>

            
            <!--<div class="d-none d-lg-block">-->
            <!--    <a href="login.php"-->
            <!--        type="button"-->
            <!--        class="custom-btn btn btn-danger"-->
            <!--        data-bs-toggle="modal"-->
            <!--        data-bs-target="#BookingModal"-->
            <!--        <a class="nav-link<?php echo ($websitepage->ref == 'Login' ? ' active' : ''); ?>" href="login.php"><?php echo $weblangs->trans("Login"); ?></a>-->
            <!--</div>-->
           
           
           
           
           
            <?php if (!isset($_SESSION['valid'])) : ?>
            <a href="login.php">
                <button class="normaldzq"><i class='bx bxs-user'></i>Votre espace client </button>
            </a>
            <?php else :?>
            <div class="login-disco">
                
            <a href="profil.php">
                <button class="normaldzq"><i class='bx bxs-user'></i>Mon espace client</button>
            </a>
            <a href="logout2.php">
               <i class='bx bx-log-out'></i>
            </a>
            </div>
            <?php endif; ?>
                
            
    </nav>
</section>






<style>
    
    :root {
    --color-first: #263c5c;
    --color-second: #f6f8fb;
    --color-third: #000000;
    }
    
    .login-disco {
        display: flex;
        gap: 20px;
        flex-direction: row;
        align-items: center;
    }
    .login-disco .bx-log-out{
        font-size: 2.2rem;
        transform: rotate(180deg);
        color: #f0f0f0;
        transition: .4s;
    }
    .login-disco .bx-log-out:hover {
        transform: translateX(10px) rotate(180deg);
    }

    .newNavbar {
        background : var(--color-first);
        display: flex;
        align-content: center;
        align-items: center;
        justify-content: space-around;
        padding: 12px 20px;
        position: relative;
        box-shadow: 0 2px 6px #00000047;
        z-index: 100;
    }
    
    .container-link {
        display: flex;
        gap: 10px;
          
    }
    
    .container-link .nav-link {
        margin: 0 20px;  
        font-family: "Roboto", sans-serif;
        font-size: 26px !important;
        color: var(--color-second) !important; 
        letter-spacing: 1px;
    }
    
    .normaldzq {
        text-transform: uppercase!important;
        font-size: 20px !important;
        color: var(--color-third)!important;
        border: none!important;
        padding: 10px 16px!important;
        display: flex!important;
        align-items: center;
        font-weight: 600;
        gap: 6px;
        letter-spacing: 1px;
        font-family: "Roboto", sans-serif !important;
        border-radius: 16px !important;
        transition: .4s;
         will-change: transform;
    }
    
    .normaldzq:hover {
        transform: scale(105%);
        color: var(--color-second) !important;
        background: #9ab4d1;
    }
    
    
     
    
    

 
    
    
</style>












</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 82); dolWebsiteIncrementCounter(9, "menu", 82);
// END PHP ?>
