<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>login</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="login" />
<meta name="description" content="login" />
<meta name="generator" content="Dolibarr 19.0.2 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="84" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="f8d31b3e" async src="/javascript.js.php?website=<?php echo $websitekey; ?>"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-login">
<?php
// Résoudre le chemin absolu vers main.inc.php
$main_inc_path = $_SERVER['DOCUMENT_ROOT'] . '/main.inc.php';

// Inclure le fichier de Dolibarr
require_once $main_inc_path;

session_start();

$login_success = false;
$error_message = '';

if (isset($_POST['submit'])) {
    // Connexion à la base de données Dolibarr
    global $db;

    if ($db) {
        // Échapper les valeurs des champs de formulaire
        $email = trim($db->escape($_POST['email']));
        $code_client = trim($db->escape($_POST['code_client']));

        // Récupérer l'utilisateur avec l'email donné
        $sql = "SELECT * FROM " . MAIN_DB_PREFIX . "societe WHERE email='" . $email . "'";
        $result = $db->query($sql);

        if ($result) {
            $row = $db->fetch_object($result);

            if ($row) {
                // Vérifier le code_client
                if ($code_client === $row->code_client) {
                    // Définir les variables de session
                    $_SESSION['valid'] = $row->email;
                    $_SESSION['societe'] = $row->nom;
                    $_SESSION['id'] = $row->rowid;
                    $login_success = true;
                } else {
                    $error_message = "Email ou code client incorrect";
                }
            } else {
                $error_message = "Email ou code client incorrect";
            }
        } else {
            $error_message = "Erreur de sélection : " . $db->lasterror();
        }
    } else {
        $error_message = "Erreur de connexion à la base de données.";
    }
}

// includeContainer('header');

?>


<style>

    :root {
    --color-first: #263c5c;
    --color-second: #f6f8fb;
    --color-third: #000000;
    }
    

    .mysection1.login {
        background: var(--color-second) !important;
        height: 100vh;
        width: 100vw;
        overflow: hidden;
        display: flex;
        position: absolute;
        top: 0;
        left: 0;
        align-items: center;
        justify-content: center;
        z-index: 500;
        overflow: hidden;
    }
    
    .login-main {
        display: flex;
        width: 92%;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
    
    .login-title {
        font-family: "JetBrains Mono", monospace;
        font-size: 42px !important;
        color: var(--color-first);
            margin: 3vh 0 !important;
    }
    
    .login-title span {
        color: var(--color-first) !important;
    }
    
    .email-input {
        border: solid 1px #263c5c;
        padding: 13px;
        font-size: 20px;
        border-radius: 14px;
    }
    
    .bodywebsite .custom-form .form-control {
        border: solid 1px #263c5c;
        padding: 13px;
        font-size: 20px;
        font-family: "Roboto", sans-serif;
        border-radius: 14px;
        margin-bottom: 30px;
        box-shadow: 0 3px 4px rgb(0 0 0 / 15%);
        transition: .4s;
    }
    
    .bodywebsite .custom-form .form-control::placeholder {
        font-size: 18px !important;
        letter-spacing: 1px;
        color: #404040a6 !important;
    }
    
    .bodywebsite .form-label {
        color: var(--color-third);
        letter-spacing: 1px;
        padding-left: 6px;
        font-family: "Roboto", sans-serif!important;
        font-weight: 400;
    }
    
    .bodywebsite .form-control:focus {
        outline: none!important;
        border: solid 2px #263c5c;
    }
    
    .login-button {
        position: relative;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    
    .login-button button {
        text-transform: uppercase !important;
    font-size: 24px !important;
    color: var(--color-second) !important;
    border: none !important;
    padding: 10px 14px !important;
    display: flex !important;
    align-items: center;
    font-weight: 600;
    gap: 13px;
    width: 45% !important;
    letter-spacing: 1px;
    font-family: "Roboto", sans-serif !important;
    border-radius: 18px !important;
    transition: .4s;
    will-change: transform;
    justify-content: center;
    background: var(--color-first) !important;
    }
    
    .login-button button:hover {
        transform: scale(105%);
        color: var(--color-first) !important;
        background: #9ab4d1 !important;
    }
    
    .login-button i {
        font-size: 24px !important;
    }
    
    .login-main .desc-text {
        color: #4a4a4a85;
        letter-spacing: 1px;
        position: relative;
        text-align: center;
        width: 45%;
        margin-bottom: 5vh;
        font-family: "Roboto", sans-serif;
    }
    
    
 
    
    
    
    
    
</style>


<section id="mysection1" class="mysection1 login" contenteditable="true">
    
    <div class="login-main">
        
                        <img src="image/ebusinessTester1/logo_zai_login.png" alt="Logo" style="max-height: 200px; width: 200px;">
                        <h2 class="login-title">Votre <span>espace</span> client</h2>
                        <p class="desc-text">Cet espace client est dédié à la consultation de vos pièces commerciales, votre solde actuel  ainsi que vos Ticket en cours de traitement. Vous pouvez consulter notre catalogue produit, aussi passer commande en ligne ou  contacter l'équipe de support.</p>
                        
                        <?php if ($error_message): ?>
                            <div class="alert alert-danger"><?php echo $error_message; ?></div>
                        <?php endif; ?>

                    <div class="col-lg-6 col-12">
                        <form class="custom-form contact-form row" action="" method="post" role="form">
                            <input type="hidden" name="action" value="sendmail">
                            <input type="hidden" name="token" value="<?php echo newToken(); ?>">

                            <div class="col-12">
                                <label for="email" class="form-label"><?php echo $weblangs->trans("Email"); ?></label>
                                <input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Saisir votre e-mail" required="">
                            </div>

                            <div class="col-12">
                                <label for="code_client" class="form-label">Code Client</label>
                                <input type="password" name="code_client" id="code_client" class="form-control" placeholder="Saisir votre code Client" required="">
                            </div>

                            <div class="login-button">
                                <button type="submit" name="submit" class="form-control">Se connecter<i class='bx bx-log-in' ></i></button>
                            </div>
                        </form>

                        <?php if ($login_success): ?>
                            <!-- Lien vers Commandes.php avec ID pour le cibler avec JavaScript -->
                            <div class="col-lg-5 col-12 ms-auto mt-3">
                                <a href="profil.php" id="commandesLink" class="butAction ms-4"></a>
                            </div>
                            <script>
                                // Script JavaScript pour redirection automatique si login réussi
                                window.onload = function() {
                                    var commandesLink = document.getElementById('commandesLink');
                                    if (commandesLink) {
                                        commandesLink.click(); // Simuler un clic sur le lien pour la redirection
                                    }
                                };
                            </script>
                        <?php endif; ?>
                    </div>
                    
                    
                </div>
        </section>
    </main>
</section>


</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 84); dolWebsiteIncrementCounter(9, "page", 84);
// END PHP ?>
