<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="en">
<head>
<title>proposition_commerciale</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="proposition_commerciale" />
<meta name="description" content="proposition_commerciale" />
<meta name="generator" content="Dolibarr 19.0.2 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="91" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="d5db4ada" async src="/javascript.js.php?website=<?php echo $websitekey; ?>"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-proposition_commerciale">
<?php
// Résoudre le chemin absolu vers main.inc.php
$main_inc_path = $_SERVER['DOCUMENT_ROOT'] . '/main.inc.php';
// Inclure le fichier de Dolibarr
require_once $main_inc_path;

session_start();
if (!isset($_SESSION['valid'])) {
    include 'login.php';
    exit;
}

// Connexion à la base de données Dolibarr
global $db;

if ($db) {
    // Récupérer l'ID de la société connectée
    $societe_id = $_SESSION['id'];

    // Initialisation des variables de recherche
    $ref = isset($_GET['ref']) ? $_GET['ref'] : '';
    $filter_statut = isset($_GET['filter-statut']) ? $_GET['filter-statut'] : ''; // Filtre statut

    // Requête SQL pour obtenir la somme totale des total_ht des propositions de la société connectée
    $query_total_ht = "SELECT SUM(total_ht) AS total_ht_sum FROM " . MAIN_DB_PREFIX . "propal WHERE fk_soc = " . intval($societe_id);
    $result_total_ht = $db->query($query_total_ht);
    $total_ht_sum = 0;

    if ($result_total_ht) {
        $row_total_ht = $db->fetch_object($result_total_ht);
        if ($row_total_ht) {
            $total_ht_sum = $row_total_ht->total_ht_sum;
        }
    }

    // Requête SQL initiale pour récupérer les propals
    $sql = "SELECT rowid AS propal_id, ref, datec, total_ht, total_ttc, total_tva, note_public, fin_validite, fk_statut 
            FROM " . MAIN_DB_PREFIX . "propal 
            WHERE fk_soc = " . intval($societe_id) . " AND fk_statut != 0 ";

    // Ajouter le critère de recherche par référence seulement si elle est définie
    if (!empty($ref)) {
        $sql .= " AND ref LIKE '%" . $db->escape($ref) . "%'";
    }

    // Ajout des conditions de filtre de statut
    if (!empty($filter_statut)) {
        if ($filter_statut == '1') {
            $sql .= " AND fk_statut = 1";
        } elseif ($filter_statut == '2') {
            $sql .= " AND fk_statut = 2";
        } elseif ($filter_statut == '3') {
            $sql .= " AND fk_statut = 3";
        }
    }

    // Exécuter la requête SQL
    $result = $db->query($sql);

    // Vérifier si la requête SQL a retourné des résultats
    if (!$result) {
        echo "Erreur dans la requête SQL: " . $db->lasterror();
    }
} else {
    echo "Erreur de connexion à la base de données";
    exit;
}
$link_to_page = dol_buildpath('detailspropale.php', 1);
$link_to_page_filter = dol_buildpath('proposition_commerciale.php', 1);
?>
<?php includeContainer('header'); ?>
<?php includeContainer('aside_bar'); ?>
<section id="mysection1" contenteditable="true">
    <main>
        <div class="ccontainer">
            <div class="table-container">
                <table class="oorder-table">
                    <thead>
                        <tr>
                            <th>N° DE PROPOSITION</th>
                            <th>Date</th>
                            <th>Date de validité</th>
                            <th>Montant_HT </th>
                            <th>Montant_tva </th>
                            <th>Montant_TTC </th>
                            <th>Note (public) </th>
                            
                            <style>
                                .filter-statut {
                                    position: absolute;
                                    top: 0;
                                    width: 100%;
                                    height: 80%;
                                    left: 10px;
                                    font-size: 14px;
                                }
                                
                                #filter-statut {
                                    opacity: 0;
                                    height: 100%;
                                    width: 100%;
                                    padding: 10px;
                                    cursor: pointer;
                                }
                                
                                .box-filter {
                                    display: flex;
                                    justify-content: center;
                                    align-items: center;
                                }
                                
                            </style>
                            
                            <th style="position: relative;">
                                <div class="filter-statut">
                                    <form action="<?php echo htmlspecialchars($link_to_page_filter); ?>" method="get">
                                        <input type="hidden" name="website" value="ebusinessTester1">
                                        <input type="hidden" name="pageref" value="proposition_commerciale">
                                        <label></label>
                                        <select name="filter-statut" id="filter-statut" onchange="this.form.submit()">
                                            <option value="" <?php if ($filter_statut == '') echo 'selected'; ?>>Tout</option>
                                            <option value="1" <?php if ($filter_statut == '1') echo 'selected'; ?>>Ouvert</option>
                                            <option value="2" <?php if ($filter_statut == '2') echo 'selected'; ?>>Signée</option>
                                            <option value="3" <?php if ($filter_statut == '3') echo 'selected'; ?>>Non-Signée</option>
                                        </select>
                                    </form>
                                </div>
                                <span class="box-filter">
                                    STATUT<i class='bx bx-filter' style="margin-left: 4px;"></i>
                                </span>
                            </th>
                            
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        // Initialisation des totaux
                        $total_ht_sum = 0;
                        $total_tva_sum = 0;
                        $total_ttc_sum = 0;

                        if ($result) {
                            while ($row = $db->fetch_object($result)) {
                                echo "<tr>";    
                                echo "<td>{$row->ref}</td>";
                                echo "<td>" . date("d/m/Y", strtotime($row->datec)) . "</td>";
                                echo "<td>" . date("d/m/Y", strtotime($row->fin_validite)) . "</td>";
                                echo "<td>" . number_format($row->total_ht, 3, ',', ' ') . " TND</td>";
                                echo "<td>" . number_format($row->total_tva, 3, ',', ' ') . " TND</td>";
                                echo "<td>" . number_format($row->total_ttc, 3, ',', ' ') . " TND</td>";
                                echo "<td>{$row->note_public}</td>";

                                // Ajouter les valeurs aux totaux
                                $total_ht_sum += $row->total_ht;
                                $total_tva_sum += $row->total_tva;
                                $total_ttc_sum += $row->total_ttc;

                                // Affichage du statut en fonction de la valeur de fk_statut
                                if ($row->fk_statut == 1) {
                                    echo "<td>Ouvert</td>";
                                } elseif ($row->fk_statut == 2) {
                                    echo "<td>Signée</td>";
                                } elseif ($row->fk_statut == 3) {
                                    echo "<td>Non-Signée</td>";
                                } else {
                                    echo "<td>Autre</td>"; // Gérer les autres cas si nécessaire
                                }

                                echo "<td><a href=\"" . htmlspecialchars($link_to_page . '?propal_id=' . $row->propal_id) . "\" class=\"aaction-btn\">Imprimer</a></td>";
                                echo "</tr>";
                            }
                            $db->free($result);
                        } else {
                            echo "<tr><td colspan='9'>Aucune Proposition trouvée</td>"; // Modifié pour correspondre au nombre de colonnes
                        }
                        ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3"><strong>Total</strong></td>
                            <td><strong><?php echo number_format($total_ht_sum, 3, ',', ' ') . " TND"; ?></strong></td>
                            <td><strong><?php echo number_format($total_tva_sum, 3, ',', ' '); ?></strong></td>
                            <td><strong><?php echo number_format($total_ttc_sum, 3, ',', ' ') . " TND"; ?></strong></td>
                            <td colspan="4"></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </main>
</section>

</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 91); dolWebsiteIncrementCounter(9, "page", 91);
// END PHP ?>
